baseURL = 'https://jiekeshi.github.io/'
languageCode = 'en-us'
title = "Jieke Shi's Homepage"

[menus]

  [[menus.main]]
    name = 'ğŸ  About'
    url = '/'
    weight = 1

  [[menus.main]]
    name = 'ğŸ“– Publications'
    url = '/publications'
    weight = 2

  [[menus.main]]
    name = 'ğŸ’¼ Services'
    url = '/services'
    weight = 3

  [[menus.main]]
    name = 'ğŸ† Awards'
    url = '/awards/'
    weight = 4

  [[menus.main]]
    name = 'ğŸ“œ CV'
    url = '/CV.pdf'
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  footer="Â© Jieke Shi | Last Update: Sep 2024"


